# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_myauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='myauthtoken',
            name='token',
            field=models.CharField(default='', max_length=300),
        ),
    ]
